# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  devhabitapi:
    image: devhabitapi
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

    environment:
      # 配置 OTEL 导出器的端点和协议
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889 # docker中运行（生产）
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:18889 # 本地运行.NET（开发）
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  devhabit.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8008:80
      - 5341:5341

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
      - 18889:18889