name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # 4 空格 ← 和上面两个对齐

jobs:
    build:
        runs-on: ubuntu-24.04 #  Ubuntu版本:24.04

        steps:
            - name: 检出代码
              uses: actions/checkout@v5 # Node.js 24

            - name: 安装 .NET 10 SDK
              uses: actions/setup-dotnet@v5 # Node.js 24
              with:
                  dotnet-version: "10.0.x"

            - name: 还原依赖
              run: dotnet restore

            - name: 构建
              run: dotnet build --configuration Release --no-restore

            - name: 运行测试
              run: dotnet test --configuration Release
